// GENERATED by ../src/build.py. Dictionaries of the PM module: { 'English text': 'translation' } per app
// language (kit8/i18n LANGUAGES). English needs none: the English text is the key.
import ar from './ar';
import bn from './bn';
import de from './de';
import es from './es';
import et from './et';
import fa from './fa';
import fr from './fr';
import hi from './hi';
import lt from './lt';
import lv from './lv';
import nl from './nl';
import pt from './pt';
import ru from './ru';
import zh from './zh';

export const PM_LOCALES: Record<string, Record<string, string>> = { ar, bn, de, es, et, fa, fr, hi, lt, lv, nl, pt, ru, zh };
