#!/usr/bin/env python3
# Builds ../locales/<lang>.ts + ../locales/index.ts from the numbered lists next to this file.
#   <lang>.txt:  N|translation      N = 1-based position of the English text in ../locales/keys.ts (PM_KEYS)
# A missing number = that text stays English. Run:  python3 kit8/pm/i18n/src/build.py
import json, os, re, sys
here = os.path.dirname(os.path.abspath(__file__))
loc = os.path.join(here, '..', 'locales')
keys = [json.loads(l.strip().rstrip(',')) for l in open(os.path.join(loc, 'keys.ts'), encoding='utf8') if l.strip().startswith('"')]
ph = lambda s: sorted(re.findall(r'\{\{\w+\}\}', s))
langs, problems = [], []
for name in sorted(os.listdir(here)):
    if not name.endswith('.txt'): continue
    lang = name[:-4]
    out = {}
    for ln, line in enumerate(open(os.path.join(here, name), encoding='utf8'), 1):
        line = line.rstrip('\n')
        if not line.strip(): continue
        m = re.match(r'(\d+)\|(.*)$', line)
        if not m: problems.append(f'{name}:{ln}: not "N|text"'); continue
        n, text = int(m.group(1)), m.group(2).strip()
        if not 1 <= n <= len(keys): problems.append(f'{name}:{ln}: no key {n}'); continue
        key = keys[n - 1]
        if key in out: problems.append(f'{name}:{ln}: key {n} twice')
        if not text: problems.append(f'{name}:{ln}: empty'); continue
        if ph(key) != ph(text): problems.append(f'{name}:{ln}: placeholders {ph(key)} != {ph(text)}')
        out[key] = text
    with open(os.path.join(loc, f'{lang}.ts'), 'w', encoding='utf8') as f:
        f.write(f"// GENERATED by ../src/build.py from ../src/{lang}.txt - edit that file, not this one.\n")
        f.write('const texts: Record<string, string> = {\n')
        for k in keys:
            if k in out: f.write(f'  {json.dumps(k, ensure_ascii=False)}: {json.dumps(out[k], ensure_ascii=False)},\n')
        f.write('};\nexport default texts;\n')
    langs.append((lang, len(out)))
with open(os.path.join(loc, 'index.ts'), 'w', encoding='utf8') as f:
    f.write("// GENERATED by ../src/build.py. Dictionaries of the PM module: { 'English text': 'translation' } per app\n// language (kit8/i18n LANGUAGES). English needs none: the English text is the key.\n")
    for lang, _ in langs: f.write(f"import {lang} from './{lang}';\n")
    f.write('\nexport const PM_LOCALES: Record<string, Record<string, string>> = { ' + ', '.join(l for l, _ in langs) + ' };\n')
print(len(keys), 'keys;', ', '.join(f'{l}: {n}' for l, n in langs))
for p in problems: print('PROBLEM', p)
sys.exit(1 if problems else 0)
