#!/usr/bin/env node
// Builds kit8/sql/run_fresh_data.sql = ALL the SQL a fresh database needs, in the right order, in ONE file for the Supabase SQL editor.
//   node kit8/sql/tools/build_run_fresh_data.js
// The separate files in kit8/sql/init stay the source (edit THEM, one file per feature); this script only concatenates them.
// Add a new file to FILES (in the order it must run) and run the script again. See kit8/sql/init/RUN_ORDER.md for what each file does.
const fs = require('fs');
const path = require('path');

const INIT = path.join(__dirname, '..', 'init');
const OUT = path.join(__dirname, '..', 'run_fresh_data.sql');

/** [file in kit8/sql/init, what it adds] - in the order they must run */
const FILES = [
  ['done/create_tables.sql', 'base tables, personTable, contractTable, the PM project / task tables, kit8_setup_def_table, pm_touch_updated_at, pm_owns_project'],
  ['update_currency_exchange_rate_types.sql', 'exchange rate TYPES (Default | Budget, as D365 FO): the key of a rate = day or day|Type'],
  ['insert_currency_exchange_rates_2025_2026.sql', 'ECB exchange rates 2025 -> 2026 (Default: every working day, Budget: the planned rate of the year) for 9 currencies; generated by build_currency_rates_sql.js'],
  ['create_product_tables.sql', 'product catalog + the shared descriptor / variant / price tables'],
  ['create_resource_role_tables.sql', 'role types, roles, role rates, descriptors seniority / workLanguage / certification'],
  ['create_management_genus_table.sql', 'management genus: costs (time / material / expense), revenue, payments'],
  ['insert_rows_resource_table.sql', 'demo human / material / expense / revenue roles; managementGenus on the role types'],
  ['create_person_type_table.sql', 'personTypeTable (Employee, Contractor) + 50 % Employee / 50 % Contractor of all persons'],
  ['create_person_descriptors.sql', 'person Properties + Variants (separate certificate rows), a contract for every person'],
  ['create_template_resource_contract_table.sql', 'templateResourceContractTable (rowOwnerGUID = management genus) + demo templates'],
  ['create_pm_task_line_table.sql', 'task_line_table + RPC pm_set_task_last_edit_place (rowJSON.lastEditPlace)'],
  ['create_user_calendar_tables.sql', 'user calendars, events, reminders'],
];

/**
 * The delete scripts, in the order they must run (the reverse of the install order). They are written into the file as a RESET section
 * at the very top, COMMENTED OUT (every line starts with "-- "), so a normal run deletes nothing: uncomment the section (or part of it)
 * and the file becomes "delete everything, then create it all again".
 */
const DELETE_FILES = [
  ['delete_pm_task_line_table.sql', 'drops task_line_table + pm_set_task_last_edit_place'],
  ['delete_template_resource_contract_table.sql', 'drops templateResourceContractTable'],
  ['delete_person_descriptors.sql', 'removes the person descriptors, variants, certificates and the demo contracts'],
  ['delete_person_type_table.sql', 'drops personTypeTable'],
  ['delete_resource_role_tables.sql', 'drops the resource role tables + their rows in the shared descriptor tables'],
  ['delete_product_tables.sql', 'drops the product catalog and the shared descriptor / variant / price tables'],
  ['delete_management_genus_table.sql', 'drops managementGenusTable'],
  ['done/delete_tables.sql', 'drops EVERYTHING of done/create_tables.sql: all projects, tasks, catalogs, persons, contracts, rates (all users!)'],
];

const bar = '-- ' + '='.repeat(95);
const parts = [];
parts.push([
  bar,
  '-- UNIVERSAL1 - ALL SQL OF A FRESH DATABASE IN ONE FILE: kit8/sql/run_fresh_data.sql',
  '-- GENERATED by kit8/sql/tools/build_run_fresh_data.js from the files of kit8/sql/init - do not edit here, edit those files and run the script again.',
  '--',
  '-- Supabase -> SQL Editor -> paste this whole file -> Run. Every part is idempotent and non-destructive (CREATE ... IF NOT EXISTS, seeds ON CONFLICT DO NOTHING),',
  '-- so it is safe to run twice. Order and what each part adds:',
  '--',
  ...FILES.map(([f, what], i) => `--   ${String(i + 1).padStart(2)}. ${f}\n--       ${what}`),
  '--',
  '-- The delete scripts are in it too, as the RESET section right below this header - COMMENTED OUT, so nothing is deleted unless you remove the "-- " signs.',
  '--',
  '-- NOT in this file, on purpose (everything a fresh database needs is already in the parts above):',
  '--   update_prices.sql, update_product_units.sql, update_product_vat.sql, rename_product_package_table.sql',
  '--                                     migrations of an OLDER database - create_product_tables.sql already creates the same result; update_product_vat.sql would',
  '--                                     also overwrite the VAT you set by hand on every run, update_product_units.sql / rename_* contain guarded DROP / RENAME',
  '--   create_prices_for_all_products_and_variants.sql',
  '--                                     ~3100 demo prices: the dashboard reads 1000 rows per table, so it would show the prices only in part (run it by hand if wanted)',
  '--   create_task_expense_input_table.sql  obsolete (the table of a removed demo)',
  bar,
  '',
].join('\n'));

const commented = (sql) => sql.split('\n').map((l) => (l.trim() === '' ? '--' : '-- ' + l)).join('\n');
const resetSql = DELETE_FILES.map(([file, what], i) => {
  const full = path.join(INIT, file);
  if (!fs.existsSync(full)) throw new Error(`missing ${file}`);
  const sql = fs.readFileSync(full, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '');
  return ['--', `-- RESET ${i + 1}. kit8/sql/init/${file}  -  ${what}`, commented(sql)].join('\n');
});
parts.push([
  bar,
  '-- RESET SECTION - IRREVERSIBLE, COMMENTED OUT: a normal run of this file deletes NOTHING.',
  '-- To start from an EMPTY database: make a backup, remove the leading "-- " of the RESET parts you want (all of them = delete everything, then the parts',
  '-- below create it all again), run the file, and put the "-- " signs back (or rebuild the file with node kit8/sql/tools/build_run_fresh_data.js).',
  '-- The parts are in the order they must run (reverse of the install order). The last one (done/delete_tables.sql) deletes the data of ALL users.',
  bar,
  resetSql.join('\n'),
  '',
].join('\n'));

for (const [file, what] of FILES) {
  const full = path.join(INIT, file);
  if (!fs.existsSync(full)) throw new Error(`missing ${file}`);
  const sql = fs.readFileSync(full, 'utf8').replace(/\r\n/g, '\n').replace(/\s+$/, '');
  parts.push(['', bar, `-- PART: kit8/sql/init/${file}`, `-- ${what}`, bar, '', sql, ''].join('\n'));
}
parts.push(`\n${bar}\n-- END of run_fresh_data.sql (${FILES.length} parts)\n${bar}\n`);

fs.writeFileSync(OUT, parts.join('\n'));
const kb = Math.round(fs.statSync(OUT).size / 1024);
console.log(`${path.relative(process.cwd(), OUT)}: ${FILES.length} parts + ${DELETE_FILES.length} commented-out delete parts, ${kb} KB`);
