#!/usr/bin/env node
// Builds kit8/sql/init/insert_currency_exchange_rates_2025_2026.sql from the Frankfurter API (ECB reference rates, no key):
//   node kit8/sql/tools/build_currency_rates_sql.js [from=2025-01-01] [to=<today>]
// Default rates = the ECB rate of every working day (a rate applies until the next one: weekends / holidays use the last working day).
// Budget rates  = ONE planned rate per currency per year, starting on 1 January: the rate of the first working day of the year.
// The SQL finds the currency by its ISO code (currencyTable.rowJSON.currencyCode), so it works with any rowGUIDs. Base: EUR.
const fs = require('fs');
const path = require('path');

const BASE = 'EUR';
const QUOTES = ['USD', 'GBP', 'CHF', 'JPY', 'CNY', 'SEK', 'NOK', 'DKK', 'PLN'];
const from = process.argv[2] || '2025-01-01';
const to = process.argv[3] || new Date().toISOString().slice(0, 10);
const OUT = path.join(__dirname, '..', 'init', 'insert_currency_exchange_rates_2025_2026.sql');

const dayNumber = (iso) => { const [y, m, d] = iso.split('-').map(Number); return Math.round(Date.UTC(y, m - 1, d) / 86400000); };

(async () => {
  const url = `https://api.frankfurter.dev/v2/rates?base=${BASE}&quotes=${QUOTES.join(',')}&from=${from}&to=${to}&providers=ECB`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Frankfurter answered ${res.status}`);
  const rows = (await res.json()).filter((r) => r && r.date && r.quote && Number(r.rate) > 0);
  const days = [...new Set(rows.map((r) => r.date))].sort();
  const byKey = new Map(rows.map((r) => [`${r.quote}|${r.date}`, Number(r.rate)]));

  // Default: every working day. Budget: the first working day of each year, dated 1 January.
  const defaults = [];
  const budgets = [];
  // the years of the requested range (the service may answer with the working day BEFORE `from`: it carries the rate over the 1 January)
  const years = [];
  for (let y = Number(from.slice(0, 4)); y <= Number(to.slice(0, 4)); y++) years.push(String(y));
  for (const q of QUOTES) {
    for (const d of days) { const r = byKey.get(`${q}|${d}`); if (r) defaults.push([q, d, r]); }
    for (const y of years) {
      const first = days.find((d) => d >= `${y}-01-01` && d.startsWith(y));
      const r = first && byKey.get(`${q}|${first}`);
      if (r) budgets.push([q, `${y}-01-01`, r, first]);
    }
  }
  const lines = [];
  lines.push(`-- =====================================================================================
-- UNIVERSAL1 - EXCHANGE RATES ${from.slice(0, 4)} -> ${to.slice(0, 4)}: kit8/sql/init/insert_currency_exchange_rates_2025_2026.sql
-- GENERATED by kit8/sql/tools/build_currency_rates_sql.js on ${new Date().toISOString().slice(0, 10)} from the Frankfurter API (ECB reference rates, base ${BASE}) - run the script again to refresh it.
-- (run AFTER done/create_tables.sql (currencyTable, currencyExchangeRateTable) and update_currency_exchange_rate_types.sql; IDEMPOTENT: ON CONFLICT DO NOTHING)
--
--   Default rates: ${defaults.length} rows = ${QUOTES.length} currencies x the ECB working days ${days[0]} .. ${days[days.length - 1]}.
--                  currencyRatio = units of the currency for 1 ${BASE}; a rate applies until the next one (weekends / holidays: the last working day).
--   Budget rates:  ${budgets.length} rows = one PLANNED rate per currency per year, dated 1 January = the rate of the first working day of that year (a budget does not
--                  follow the daily rate). rowParentGUID = 'YYYY-MM-DD|Budget', rowJSON.rateType = 'Budget'.
--   The currency is found by its ISO code, so the script works with any rowGUID of currencyTable. A code that is not in currencyTable is skipped.
-- =====================================================================================

DO $$
BEGIN
  IF to_regclass('public."currencyExchangeRateTable"') IS NULL OR to_regclass('public."currencyTable"') IS NULL THEN
    RAISE EXCEPTION 'Run kit8/sql/init/done/create_tables.sql first (currencyTable, currencyExchangeRateTable)';
  END IF;
END $$;
`);
  const emit = (title, kind, rowsOf) => {
    lines.push(`-- ---- ${title} ----`);
    lines.push(`INSERT INTO public."currencyExchangeRateTable" ("rowOwnerGUID", "rowParentGUID", "orderInList", "rowJSON")
SELECT c."rowGUID",
       CASE WHEN v.kind = 'Budget' THEN v.day || '|Budget' ELSE v.day END,
       -(((v.day)::date - DATE '1970-01-01')::int),
       jsonb_build_object('startingDate', v.day, 'currencyRatio', v.ratio, 'rateType', v.kind, 'rateSource', v.source, 'rateBase', '${BASE}')
  FROM (VALUES`);
    const rows = rowsOf;
    const out = rows.map(([q, d, r, src], i) => `    ('${q}', '${d}', ${r}, '${kind}', '${src}')${i === rows.length - 1 ? '' : ','}`);
    lines.push(out.join('\n'));
    lines.push(`  ) AS v(code, day, ratio, kind, source)
  JOIN public."currencyTable" c ON upper(c."rowJSON"->>'currencyCode') = v.code
ON CONFLICT DO NOTHING;
`);
  };
  emit(`Default rates: the ECB rate of every working day, ${days[0]} .. ${days[days.length - 1]}`, 'Default', defaults.map(([q, d, r]) => [q, d, r, 'frankfurter-ecb']));
  emit('Budget rates: the planned rate of the year (the first working day), dated 1 January', 'Budget', budgets.map(([q, d, r]) => [q, d, r, 'budget-plan']));
  lines.push("NOTIFY pgrst, 'reload schema';\n");
  fs.writeFileSync(OUT, lines.join('\n'));
  console.log(`${path.relative(process.cwd(), OUT)}: ${defaults.length} Default + ${budgets.length} Budget rows, ${days[0]} .. ${days[days.length - 1]}, ${Math.round(fs.statSync(OUT).size / 1024)} KB`);
})().catch((e) => { console.error(e); process.exit(1); });
